### PR TITLE
Refactor into structured files

### PR DESCRIPTION
**Pull request by TylerRockwell**
### Why?
* Smaller files are easier to digest and edit

### What Changed
* Refactored single monolithic file into smaller, namespaced classes and files
* The only _code_ change is that `Error` now inherits from `StandardError` instead of `Exception`

### CODE REVIEW

**Comment by fotinakis** [comment]
Hmm, after going through this a few times I guess I'm ok with it, not convinced it actually makes it easier to edit but it's a judgement call. Some of the nodes and root logic are big enough that this is helpful, but all the module nesting and tiny 1-line classes make it less so. Overall, it's fine with me though feels unnecessary—but, if this makes it easier for you and people to contribute then I'm 👍 

The one thing I'd like to change is to revert the changes with errors—1) remove the `Errors::` namespace and keep errors nested inside the `Swagger::Blocks::` namespace so that they don't change, 2) don't split errors by file, if you do split out errors put them all in one file. Let's keep the  `StandardError` change, that's positive.

**Comment by TylerRockwell** [comment]
Thanks for looking over the PR. I had some of the same feelings as well, but ultimately felt that the code would be easier to work on this way. You're right, though, it really is a subjective call.

I went ahead and removed the namespace from the Errors and moved them all into a single file.

**Comment by dkniffin** [comment]
Yea, I agree it's not completely necessary, but it matches the pattern that most other gems use, so I think it just _feels_ a bit cleaner.

**Comment by fotinakis** [comment]
Thanks for contributing! Would you two like to take on the v1.2 code deletion as well? Then I can prep a 2.0.0 release of this gem.

**Comment by TylerRockwell** [comment]
Yeah I/we are looking into doing that in the near future.

**Pull request merged**
