### PR TITLE
Allow root node to be extended

### PR DESCRIPTION
**Pull request by justinhoward**
If the root_node method is called multiple times, extend the existing
root node instead of overwriting it.

### CODE REVIEW

**Comment by fotinakis** [comment]
Why in the world are the tests passing...
https://github.com/fotinakis/swagger-blocks/blob/ed779b7d136e9fc2ebabdd00b37dd33e193f009d/spec/lib/swagger_v2_blocks_spec.rb#L285

Also, would love to see a test for this behavior, including merging of inline keys.

**Comment by justinhoward** [comment]
Yeah, just noticed that myself when I read your comment. I'll do some more investigating. My guess is that it's because swagger_root is being called twice in the same class.

**Comment by justinhoward** [comment]
For inline keys, I noticed that they are currently being ignored for successive `swagger_schema` and `swagger_path` calls, so I didn't implement them for `swagger_root` either. Those need to be fixed up as well, but I may do that as a separate PR.

**Comment by justinhoward** [comment]
Hmm, I investigated a bit more, and this is going to be harder than I originally thought. Right now, the methods on `RootNode` check the swagger version immediately when called. That means that if the version is defined in one class, and I'm calling the `response` method from another class, it throws a `NotSupportedError`, because it doesn't know the version. The obvious solution would be to defer validation until build time, but that will require more work. I'll see what I can do.

**Comment by fotinakis** [comment]
Or, we could have a PR before this one that entirely removes support for v1.2. Then, do this PR. Then tag everything as 2.0.

**Comment by alexkravets** [comment]
+1 for 2.0 version

**Comment by fotinakis** [comment]
Let's remove all the 1.2 support code and then revisit this PR. Anybody feel like making a PR to remove 1.2 features and files?

**Comment by TylerRockwell** [comment]
@fotinakis When you say remove 1.2 support code, do you mean remove all code relating to 1.2? (i.e. this gem will cease to work with Swagger 1.2)

**Comment by fotinakis** [comment]
Yes @TylerRockwell — at that point we would release v2.0.0 of this gem and make sure people know it's only compatible with Swagger 2.0.

**Pull request closed without merging**
