### PR TITLE
WIP: Add basic support for openapi

### PR DESCRIPTION
**Pull request by gabrieltaylor**
Adds support for PetStore OpenAPI 3 example.

Support for OpenAPI 3 is not feature complete.

## TODO
- Add support for callbacks ✅ 
- Add support for links [example](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/link-example.yaml) ✅ 
- Add support for examples [example](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/api-with-examples.yaml) ✅ 
- Add support for authentication schemes ✅ 
- Expand tests

### CODE REVIEW

**Comment by gabrieltaylor** [comment]
@fotinakis I think that this is ready for your review. Looking forward to hearing your thoughts.

**Comment by atomiyama** [comment]
@fotinakis we need oneOf!!!

**Comment by haseleyi** [comment]
Would love to see this feature supported :)

**Comment by auscaster** [comment]
It seems like a lot of work has gone into this, any chance of getting it merged?

**Comment by pascalbetz** [comment]
Or any feedback on why it has not been merged so far?  
Is there something we can do?
What is missing? What could/should be done differently?

We use swagger-blocks and this PR contains features that would be useful to us (the gem is already useful to us. Even without this PR. Many thanks).

**Comment by gabrieltaylor** [comment]
@fotinakis It should be backwards compatible as the v2 tests still pass, however, given the number of changes and the fact that it adds support for a major version change of Open API, a major version bump of swagger-blocks might be safer.

**Comment by fotinakis** [comment]
Thanks for the great work here.

Released as a major bump to gem version `3.0.0` — if there bugs we can fix them and release there.

**Comment by auscaster** [comment]
Nice one Mike! Thanks for merging :)

**Comment by PhilippeChab** [comment]
The README should be updated to reflect this merge.

**Pull request merged**
